{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-normalized-cache-api/2.5.5-IR/apollo-normalized-cache-api-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-normalized-cache-api",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "iosSimApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-normalized-cache-api.klib",
          "url": "apollo-normalized-cache-api-ios-x64-2.5.5-IR.klib",
          "size": 43033,
          "sha512": "55f2fbaad5f783298b47ab0943f72aa88187349c4fab7853c5598bbd9074cca1e55c92c7d9a9800f8b6c4c042c00a0c938d41cdc4c5fd37ab37aec5762e5515b",
          "sha256": "735e4a0491a1cd21d831d0b4321c796f1cd25683fe4c2e66f2c99669775808e2",
          "sha1": "58e9e5e5956b165aa8f8b0324fe34b1cf76680ea",
          "md5": "cd6abedd44dc73fa6dc4c191fe7a44c3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-api-metadata/2.5.5-IR/apollo-normalized-cache-api-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-api-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
