{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-normalized-cache-sqlite/2.5.5-IR/apollo-normalized-cache-sqlite-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-normalized-cache-sqlite",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-normalized-cache-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-normalized-cache-sqlite-debug.aar",
          "url": "apollo-normalized-cache-sqlite-android-debug-2.5.5-IR.aar",
          "size": 54004,
          "sha512": "00f5985f94dbe0e0d3f07873b175db18d0444ee5cbabb074447bde5472ee3a01c491e7258723f7270c93c654b00a09f05e7b00ba0787c32faa425b7572baefce",
          "sha256": "e76d1174e0f71fa40ccc46615ef257a8bae7b888720f4d20e04f161eb0bbb57f",
          "sha1": "e783fc64cba9a9593699df4a2520310edccb0d79",
          "md5": "868fc3ed0700e6a417c011cdec3df820"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-normalized-cache-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-normalized-cache-sqlite-debug.aar",
          "url": "apollo-normalized-cache-sqlite-android-debug-2.5.5-IR.aar",
          "size": 54004,
          "sha512": "00f5985f94dbe0e0d3f07873b175db18d0444ee5cbabb074447bde5472ee3a01c491e7258723f7270c93c654b00a09f05e7b00ba0787c32faa425b7572baefce",
          "sha256": "e76d1174e0f71fa40ccc46615ef257a8bae7b888720f4d20e04f161eb0bbb57f",
          "sha1": "e783fc64cba9a9593699df4a2520310edccb0d79",
          "md5": "868fc3ed0700e6a417c011cdec3df820"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-sqlite-metadata/2.5.5-IR/apollo-normalized-cache-sqlite-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-sqlite-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
