{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-zipfilesystem-multiplatform/3.0.0-IR/okio-zipfilesystem-multiplatform-3.0.0-IR.module",
    "group": "com.squareup.okio",
    "module": "okio-zipfilesystem-multiplatform",
    "version": "3.0.0-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "faq5qxiuizeffprgxbc6heg2ni"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        }
      ],
      "files": [
        {
          "name": "okio-zipfilesystem-jvm-3.0.0-IR.jar",
          "url": "okio-zipfilesystem-3.0.0-IR.jar",
          "size": 21619,
          "sha512": "875bacccf71bf773cd4d0f0cbd98e846c232763ecb7e9c2e94f964e658159d14edd9481dce6a10183ee5efedb2aab0d72f87cecda4683937dc65fb0b80dbf85b",
          "sha256": "205556b30e51dd06fdace98c251bd733097fa43589ddee3ee957cb601796ceaf",
          "sha1": "4151228cb07ade3e89a480ecb25da3c392711803",
          "md5": "c7e87f88d1920b9fa08388c73896d103"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        }
      ],
      "files": [
        {
          "name": "okio-zipfilesystem-jvm-3.0.0-IR.jar",
          "url": "okio-zipfilesystem-3.0.0-IR.jar",
          "size": 21619,
          "sha512": "875bacccf71bf773cd4d0f0cbd98e846c232763ecb7e9c2e94f964e658159d14edd9481dce6a10183ee5efedb2aab0d72f87cecda4683937dc65fb0b80dbf85b",
          "sha256": "205556b30e51dd06fdace98c251bd733097fa43589ddee3ee957cb601796ceaf",
          "sha1": "4151228cb07ade3e89a480ecb25da3c392711803",
          "md5": "c7e87f88d1920b9fa08388c73896d103"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-zipfilesystem-metadata/3.0.0-IR/okio-zipfilesystem-metadata-3.0.0-IR.module",
        "group": "com.squareup.okio",
        "module": "okio-zipfilesystem-metadata",
        "version": "3.0.0-IR"
      }
    }
  ]
}
