{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.apollo",
    "module": "apollo-http-cache-api",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-http-cache-api-2.5.5-IR.jar",
          "url": "apollo-http-cache-api-2.5.5-IR.jar",
          "size": 10265,
          "sha512": "8fba133d3b66427ca9c08e9ddfa2ce4b10ef8845fcb74c56c704588e9437b55f300b65a5d2bcdf9e53c8c6ba186a872ecd13305599202fde7948b3ffa218ed3f",
          "sha256": "facae8d19a354ec466a1d0518671c9f6c8aa61d7c3aa4cef4b87b9695e0bc3aa",
          "sha1": "3b604e26d869e63e9ddecdd322d74fc563b08862",
          "md5": "e0415fcaaa11d665b682d01f765164d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-http-cache-api-2.5.5-IR.jar",
          "url": "apollo-http-cache-api-2.5.5-IR.jar",
          "size": 10265,
          "sha512": "8fba133d3b66427ca9c08e9ddfa2ce4b10ef8845fcb74c56c704588e9437b55f300b65a5d2bcdf9e53c8c6ba186a872ecd13305599202fde7948b3ffa218ed3f",
          "sha256": "facae8d19a354ec466a1d0518671c9f6c8aa61d7c3aa4cef4b87b9695e0bc3aa",
          "sha1": "3b604e26d869e63e9ddecdd322d74fc563b08862",
          "md5": "e0415fcaaa11d665b682d01f765164d0"
        }
      ]
    }
  ]
}
