{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-fakefilesystem-multiplatform/3.0.0-IR/okio-fakefilesystem-multiplatform-3.0.0-IR.module",
    "group": "com.squareup.okio",
    "module": "okio-fakefilesystem-multiplatform",
    "version": "3.0.0-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "faq5qxiuizeffprgxbc6heg2ni"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        }
      ],
      "files": [
        {
          "name": "okio-fakefilesystem.klib",
          "url": "okio-fakefilesystem-watchosx86-3.0.0-IR.klib",
          "size": 28724,
          "sha512": "2dc048279ee98164bd71137c2fb030344a4b23afcbca1df06b9775c6826e1f27e895a240761a4ab21defe37c7017bf4b5163be3e6fe2ebd697ffaf40b660b94c",
          "sha256": "cdde5df17dd75341480e1e06d42c4d642229279309d9bf8eafdb108825e639ef",
          "sha1": "2e9e4b996b17d2e1720443616e86acb5432ad206",
          "md5": "9408afd93a2504507fd84528745400cf"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-fakefilesystem-metadata/3.0.0-IR/okio-fakefilesystem-metadata-3.0.0-IR.module",
        "group": "com.squareup.okio",
        "module": "okio-fakefilesystem-metadata",
        "version": "3.0.0-IR"
      }
    }
  ]
}
