{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-runtime-kotlin/2.5.5-IR/apollo-runtime-kotlin-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-runtime-kotlin",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-runtime-kotlin-jvm-2.5.5-IR.jar",
          "url": "apollo-runtime-kotlin-jvm-2.5.5-IR.jar",
          "size": 160478,
          "sha512": "385c472fcf17b52af5bb182234f23e2d53a26e76c88a86fa155581f2ba231db07651e200cbd481f1ec363b8015ab3e2024c34fa726e1a0b4807952f10e151bfe",
          "sha256": "14bc83b9eda4770494fceb8b3e8c3f9efa1aa5e2ce13b0452c21aded724bc9e7",
          "sha1": "85438755b9d7bcd09082e20800117098229a0b36",
          "md5": "8c33acae9e43a8f1a0a750d62a5c3d4c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-runtime-kotlin-jvm-2.5.5-IR.jar",
          "url": "apollo-runtime-kotlin-jvm-2.5.5-IR.jar",
          "size": 160478,
          "sha512": "385c472fcf17b52af5bb182234f23e2d53a26e76c88a86fa155581f2ba231db07651e200cbd481f1ec363b8015ab3e2024c34fa726e1a0b4807952f10e151bfe",
          "sha256": "14bc83b9eda4770494fceb8b3e8c3f9efa1aa5e2ce13b0452c21aded724bc9e7",
          "sha1": "85438755b9d7bcd09082e20800117098229a0b36",
          "md5": "8c33acae9e43a8f1a0a750d62a5c3d4c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-runtime-kotlin-metadata/2.5.5-IR/apollo-runtime-kotlin-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-runtime-kotlin-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
