{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-normalized-cache-sqlite/2.5.5-IR/apollo-normalized-cache-sqlite-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-normalized-cache-sqlite",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "iosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-normalized-cache-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "1.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-normalized-cache-sqlite.klib",
          "url": "apollo-normalized-cache-sqlite-ios-arm64-2.5.5-IR.klib",
          "size": 34692,
          "sha512": "c8cfb9b3356077afbe8b93b6cad9cd013653ef6b55fcb72de9da26b6a927904561435fad1eac95804a6582727d8bf9993b396eb9fbee641f13f666c86bcc1180",
          "sha256": "2ec7d2e81016af67f7148ea3925a786c9b03e975324952fe3448734cbab21a67",
          "sha1": "96fa757d57d3d5c3ef415bf87d0f373b8f47cd1b",
          "md5": "eaa001318d3e0d0335b08a60f6e89908"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-sqlite-metadata/2.5.5-IR/apollo-normalized-cache-sqlite-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-sqlite-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
