{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.apollo",
    "module": "apollo-normalized-cache",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-normalized-cache-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-normalized-cache-metadata-2.5.5-IR.jar",
          "url": "apollo-normalized-cache-2.5.5-IR.jar",
          "size": 6261,
          "sha512": "4f3cbd742b9c234995fcea48e5168b9fb608a4209a3a099b4138aa7d82443d06df366ae58c59dc09668074d408dd293b56446e782b98d5dedebb3b559f85c73f",
          "sha256": "02927183436fb4e8cdc513db1a8a3a5293de0ebd2991155497d0105640600e9d",
          "sha1": "9dc6e28e2ee3db17417d4f13e45d6783e6bc4016",
          "md5": "20febdab654d937310c856a5b55e0cb6"
        }
      ]
    },
    {
      "name": "iosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-ios-arm64/2.5.5-IR/apollo-normalized-cache-ios-arm64-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-ios-arm64",
        "version": "2.5.5-IR"
      }
    },
    {
      "name": "iosSimApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-ios-x64/2.5.5-IR/apollo-normalized-cache-ios-x64-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-ios-x64",
        "version": "2.5.5-IR"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-jvm/2.5.5-IR/apollo-normalized-cache-jvm-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-jvm",
        "version": "2.5.5-IR"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-jvm/2.5.5-IR/apollo-normalized-cache-jvm-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-jvm",
        "version": "2.5.5-IR"
      }
    }
  ]
}
