{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-api/2.5.5-IR/apollo-api-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-api",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "iosSimApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-api.klib",
          "url": "apollo-api-ios-x64-2.5.5-IR.klib",
          "size": 188897,
          "sha512": "3d72cfe2f9d4ed7b548b6ed4a892a9d5540a779ed825c465507cd0f66be9e5f7fa5df6c74674894f540b8b750e278c16461c742a2095525a3e350d742f067adf",
          "sha256": "55edcec1f3ee4297860321f82946efd766559bd7d31c49f0d8cf2a706737289e",
          "sha1": "4a8297817a22aa552f2133e8449f5ca1f13e77cf",
          "md5": "1c58b1b66edbe6e790eb87e3b461eda6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-api-metadata/2.5.5-IR/apollo-api-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-api-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
