{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.apollo",
    "module": "apollo-rx3-support",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-rx3-support-2.5.5-IR.jar",
          "url": "apollo-rx3-support-2.5.5-IR.jar",
          "size": 20301,
          "sha512": "e6e648a866f78625e2a1401591d01d73e59a7c188568a05732b10cabf940c05c3cc9fc563cd314eead6051b174ffd96ef81a6b3d42ba8b3128c976d21d8ee6d0",
          "sha256": "3ab5b0e1459cf957e7f671d5f197f5336a18221054b61f291fde0bdfd66c8873",
          "sha1": "77e29622f3d965fb14e6470cd4ed8f343a0216e4",
          "md5": "36f6c79d3be1b431b3a30906cad66d32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-runtime",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-rx3-support-2.5.5-IR.jar",
          "url": "apollo-rx3-support-2.5.5-IR.jar",
          "size": 20301,
          "sha512": "e6e648a866f78625e2a1401591d01d73e59a7c188568a05732b10cabf940c05c3cc9fc563cd314eead6051b174ffd96ef81a6b3d42ba8b3128c976d21d8ee6d0",
          "sha256": "3ab5b0e1459cf957e7f671d5f197f5336a18221054b61f291fde0bdfd66c8873",
          "sha1": "77e29622f3d965fb14e6470cd4ed8f343a0216e4",
          "md5": "36f6c79d3be1b431b3a30906cad66d32"
        }
      ]
    }
  ]
}
