{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-api/2.5.6/apollo-api-2.5.6.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-api",
    "version": "2.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "m5jmzwi4pfa6nj7mvwjw64gywu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-api-jvm-2.5.6.jar",
          "url": "apollo-api-jvm-2.5.6.jar",
          "size": 215149,
          "sha512": "e217e7c468e94e7b4bc5bbdef9ca0ed6b31f7ce8ce5b1cf2ce347d6be9609232ff631ef9eb8ee9e0436eae5168027da1ece66e538f28bf7b0ef50268d590da13",
          "sha256": "8fa51b00a1c665f4044231ad9efb036b0d3530562f387147299c3f65d08a0250",
          "sha1": "336cdc5ccb78a3cf1fe2c4d12ac93ed40e2f28bc",
          "md5": "747d8f8d96cd87611baeb83cc33b89ab"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-api-jvm-2.5.6.jar",
          "url": "apollo-api-jvm-2.5.6.jar",
          "size": 215149,
          "sha512": "e217e7c468e94e7b4bc5bbdef9ca0ed6b31f7ce8ce5b1cf2ce347d6be9609232ff631ef9eb8ee9e0436eae5168027da1ece66e538f28bf7b0ef50268d590da13",
          "sha256": "8fa51b00a1c665f4044231ad9efb036b0d3530562f387147299c3f65d08a0250",
          "sha1": "336cdc5ccb78a3cf1fe2c4d12ac93ed40e2f28bc",
          "md5": "747d8f8d96cd87611baeb83cc33b89ab"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-api-metadata/2.5.6/apollo-api-metadata-2.5.6.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-api-metadata",
        "version": "2.5.6"
      }
    }
  ]
}
