{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-normalized-cache-api/2.5.5-IR/apollo-normalized-cache-api-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-normalized-cache-api",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "iosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-normalized-cache-api.klib",
          "url": "apollo-normalized-cache-api-ios-arm64-2.5.5-IR.klib",
          "size": 43050,
          "sha512": "be32d5e16d0c06a9e184190161a7c00842921106b5b0be6c7c41005d7fc93eb8798490edf41a2dc5004bb28a7b8298dcdfb9a6655b22b685142597cf1b28afc4",
          "sha256": "792aa26203720ba99d5f7ad59d0eb6c9fa6a2655dd845466f154e149900fb2b5",
          "sha1": "76e140ee838d429334adb619a811b1bd561195a1",
          "md5": "c2c28dd1e08698ae87df69e2970a6d9a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-api-metadata/2.5.5-IR/apollo-normalized-cache-api-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-api-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
