{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.apollo",
    "module": "apollo-runtime",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-normalized-cache",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-http-cache-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-runtime-2.5.5-IR.jar",
          "url": "apollo-runtime-2.5.5-IR.jar",
          "size": 295786,
          "sha512": "9b91185ff84c4a0daf5edad6e53aaed58b4de34e9782804338b3dff9a15df0349c02fc07c61783d48e28a910b2d12d1439de4a1792d0384c28f84378dd97c726",
          "sha256": "a6e701079de2630e1ff03d12865076c83a5354d1f18633d882074cc8212b37b4",
          "sha1": "b1209169334c9943bc9eea18b8316949a574786f",
          "md5": "c954c3d8bc6682f9584c608c5e40ac55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-normalized-cache",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-http-cache-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-runtime-2.5.5-IR.jar",
          "url": "apollo-runtime-2.5.5-IR.jar",
          "size": 295786,
          "sha512": "9b91185ff84c4a0daf5edad6e53aaed58b4de34e9782804338b3dff9a15df0349c02fc07c61783d48e28a910b2d12d1439de4a1792d0384c28f84378dd97c726",
          "sha256": "a6e701079de2630e1ff03d12865076c83a5354d1f18633d882074cc8212b37b4",
          "sha1": "b1209169334c9943bc9eea18b8316949a574786f",
          "md5": "c954c3d8bc6682f9584c608c5e40ac55"
        }
      ]
    }
  ]
}
