{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-multiplatform/3.0.0-IR/okio-multiplatform-3.0.0-IR.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "3.0.0-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "faq5qxiuizeffprgxbc6heg2ni"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "okio.klib",
          "url": "okio-iosarm64-3.0.0-IR.klib",
          "size": 307162,
          "sha512": "30ce8d181556ad18ad6f9de6439496fb79af90721c06626ebdf0de4c90a522d2cc6a03a77acd530edd989d9e5f6c9a67c730b190dd1d06603dad662f47ef404b",
          "sha256": "cb982505b369b2f8cff23103980b3028624f3970117c71f210210c22576e944b",
          "sha1": "6007b1171a06cb997a07782b23592666bbc0dedd",
          "md5": "bcba9f580f2290ac6a91ea62c040405b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/3.0.0-IR/okio-metadata-3.0.0-IR.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "3.0.0-IR"
      }
    }
  ]
}
