{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-normalized-cache/2.5.5-IR/apollo-normalized-cache-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-normalized-cache",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "iosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-normalized-cache-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-normalized-cache.klib",
          "url": "apollo-normalized-cache-ios-arm64-2.5.5-IR.klib",
          "size": 31973,
          "sha512": "c09360550db33986e665970ee2b550f3f3d32822c7539d048ea36372bb79aa827bc5e207c524f858d7ad59553cad4ba369b70277bc2a2c8b4f713ae018d11e62",
          "sha256": "021ac002fdfae2256164c7493fe0cac2a5de7c38f68e4fa64ba06c1d875cb882",
          "sha1": "65bbdc63244f2eab61d111f34df5c41d27d64898",
          "md5": "f839ee4c1039a2ae223bf0130c29e1c6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-normalized-cache-metadata/2.5.5-IR/apollo-normalized-cache-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-normalized-cache-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
