{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-watchosx86/3.0.0-IR/okio-watchosx86-3.0.0-IR.module",
    "group": "com.squareup.okio",
    "module": "okio-watchosx86",
    "version": "3.0.0-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "faq5qxiuizeffprgxbc6heg2ni"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "okio-metadata-3.0.0-IR.jar",
          "url": "okio-metadata-3.0.0-IR.jar",
          "size": 22948,
          "sha512": "c3c028452864daa3551a552e1483bdc05f2d5d8f5a3e961bc8c91a3a9bf61d4f0d295103403a55cef3ad7cdce2f3b93dc60055899dbdf916fc3ee60b84d70f83",
          "sha256": "51e91ded20bc3f0cbd950d2fa530d5f5af041bce27ce06c8c5fb52b94f7af334",
          "sha1": "658c4323ad4ade073688f3d579604cfbc51552ee",
          "md5": "435425c90ec1a006c231e342602fa111"
        }
      ]
    }
  ]
}
