{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-runtime-kotlin/2.5.5-IR/apollo-runtime-kotlin-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-runtime-kotlin",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "iosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-runtime-kotlin.klib",
          "url": "apollo-runtime-kotlin-ios-arm64-2.5.5-IR.klib",
          "size": 85502,
          "sha512": "9e89e67c1924c41e28a6d3120797c65a82488c0ef456d5fb7940396d7aefdc1e61779dfb5f1bf923948180145b319db6bdb67a037d8c1abcc856b51424a819d2",
          "sha256": "f5fa6de2d106a3526fd070077b53c75a3af93d552129f5c1d26fb3a3bb65a082",
          "sha1": "e9eb81a05ebb700d026f877c96373cea6873ff2d",
          "md5": "67a238911f3b560730f4e02a72bf71fd"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-runtime-kotlin-metadata/2.5.5-IR/apollo-runtime-kotlin-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-runtime-kotlin-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
