{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-api/2.5.5-IR/apollo-api-2.5.5-IR.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-api",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "iosApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio-multiplatform",
          "version": {
            "requires": "3.0.0-IR"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-api.klib",
          "url": "apollo-api-ios-arm64-2.5.5-IR.klib",
          "size": 188913,
          "sha512": "ec045a85a6c26c9fe986f3a61200a76f7afed8a79f99eabc5763afeb4b53cf8300f040ff220e9515851eb7b82fda2826697cb5d6dca864bc3dfdf5705c3ca703",
          "sha256": "fc28a4ede283c589e17f1e041f9d681d23b86e92fb316edcb9649a63825e88f2",
          "sha1": "03e70e047e7a4c0cbf5296b4b0018a4c885dbaf6",
          "md5": "eb7a94a6316a0d0f5d22a2d5d7f660cb"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../apollo-api-metadata/2.5.5-IR/apollo-api-metadata-2.5.5-IR.module",
        "group": "com.apollographql.apollo",
        "module": "apollo-api-metadata",
        "version": "2.5.5-IR"
      }
    }
  ]
}
