{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apollographql.apollo",
    "module": "apollo-compiler",
    "version": "2.5.5-IR",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "wygorj6an5gdldeprsn2flpu2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-compiler-2.5.5-IR.jar",
          "url": "apollo-compiler-2.5.5-IR.jar",
          "size": 948558,
          "sha512": "1de54100e519e5ca73b41c63844dcff1788e14848e65b57468e959341064619af8968633144fd3f587d0c4ccb35990c5c11a1a192d5e8f700db1f9aeb359c4f5",
          "sha256": "a56657e48607ea72371992657130f3faaf78ffae8b1313dce022357868e9db39",
          "sha1": "c8f1c8903d51ae82689827a7f30bbba94afb4ea0",
          "md5": "f23816660751485d6ef7ed0b97cd5f81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "2.5.5-IR"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-compiler-2.5.5-IR.jar",
          "url": "apollo-compiler-2.5.5-IR.jar",
          "size": 948558,
          "sha512": "1de54100e519e5ca73b41c63844dcff1788e14848e65b57468e959341064619af8968633144fd3f587d0c4ccb35990c5c11a1a192d5e8f700db1f9aeb359c4f5",
          "sha256": "a56657e48607ea72371992657130f3faaf78ffae8b1313dce022357868e9db39",
          "sha1": "c8f1c8903d51ae82689827a7f30bbba94afb4ea0",
          "md5": "f23816660751485d6ef7ed0b97cd5f81"
        }
      ]
    }
  ]
}
